### ISSUE TITLE
ENOENT: no such file or directory.... (taking screenshots)

### ISSUE THREAD

**Issue by tbowmo** [papa-pep/jasmine-trx-reporter#14]
I'm using jasmine-trx-reporter to generate test reports in our azure project, occasional I see the following error in our logs:

- Error: ENOENT: no such file or directory, open 'C:\AzureAgentUI14\_work\4\s\src\Gandalf.Web\reports\GANDALF_CHROME_@US6851 Edit existing Ansaettelesforhold\In\06428e82-d802-4e4b-9dfc-d0e6e73964dc\ca1896ff-4606-4524-bda8-7705d0b09228.png'

I have set jasmine-trx-reporter to only take screenshots on failure, if I look at the reports generated there is a sceenshot attached, but with another filename, for the above failure I see the following filename:
f7db0050-77e4-4ed9-8484-5a4f4d4d1b7a.png (probably a new screenshot taken, because the test "failed"  with the ENOENT error above)

My Jasmine trx reporter setup is as follows:
 
```
var trx = require("jasmine-trx-reporter");
return browser.getCapabilities().then(function (caps) {
  var browserName = caps.get("browserName").toUpperCase();

  var jasmineTrxConfig = {
    reportName: "Protractor Test Results",
    folder: "reports",
    outputFile: "",
    browser: "GANDALF_" + browserName,
    groupSuitesIntoSingleFile: false,
    takeScreenshotsOnlyOnFailures: true
  };
  jasmine.getEnv().addReporter(new trx(jasmineTrxConfig));
});
```

The hosts is running windows server 2012 (if that matters)

**Comment by papa-pep** [comment]
One thing you could try would be cleaning out whatever directory you are writing images to at the end of each run.  If that doesn't solve it, then I'm afraid you'll need to do some more troubleshooting.

**Comment by tbowmo** [comment]
The reports folder is cleaned on every start of a test run.

It seems that it tries to write an image file, even though it haven't failed (no other error is logged for that test step, than the ENOENT error). What makes it harder, is that it seems to be a bit random when it shows up.

anyways, I'll try and do more debugging on our azure setup.

**Comment by tbowmo** [comment]
Further debugging.. It seems that in some cases it first writes the trx file for a previous step, after a new one has started, which has replaced runDeploymentRoot in the meantime.

Below is a log from a single testrun spec file:
[single-spec.log](https://github.com/papa-pep/jasmine-trx-reporter/files/1656064/single-spec.log)

spec file is generally formatted like the following:
```
describe('blablah', ()=>{
  it('do some initial thing', async() => {
  });
  it('do something else', async() => {
  });
  describe('operation 1', () => {
    it('test 1a', async() => {
    });
    it....
    it....
  });
  describe('operation 2', () => {
    it('test 1b', async() => {
    });
    it....
    it...
  });
  describe....
});
```

It _seems_ like if it is failing in 'do something else', then the report is first written when "test 1a" under describe "operation 1", When the trx report file is written, then the runDelploymentRoot is suddenly changed, and the node-trx module fails in writing the trx file, because it cannot find the referenced png file (or so it seems)

Look around line 485 in the attached log file.

My fork of the project includes the console.log() statements that I used to generate the attached log files.

As a sidenote, to reproduce it on my local machine, I have set up protractor to run 15 concurrent browsers on my machine, and start moving them around randomly while testing.

**Comment by tbowmo** [comment]
Further invertigations..

While developing new tests today, I had two spec files like the following:
```
// File test-a.spec.ts
describe('Spec A', () => {
    it('test 1', async() => {
       expect(true).toBe(true);
    });

    it('test 2', async() => {
       expect(true).toBe(true);
    });

    it('test 3', async() => {
       expect(true).toBe(false);
    });
});

// File test-b.spec.ts
describe('Spec B', () => {
    it('test 4', async() => {
       expect(true).toBe(true);
    });

    it('test 5', async() => {
       expect(true).toBe(true);
    });

    it('test 6', async() => {
       expect(true).toBe(false);
    });
});
```

With a setup like the above. When it reaches test 5 in test-b.spec.ts, it results in the ENOENT error. Even though the test should pass.

If I set test 2 (in test-a.spec.ts) to fail, and test 3 to pass, then I do not see the error in test 5.

I tried to add a delay of 5 seconds to the end of writeResultFile() in jasmine-trx-reporter, in order to make sure that it had written the file before continuing. but that didn't solve anything.

I will see if I can create a dummy test suite, that can be run without the company systems..

**Comment by tbowmo** [comment]
test project to verify the error is available here: https://github.com/tbowmo/jasmine-trx-report-fail

**Comment by papa-pep** [comment]
Wow that is a strange issue.  This might actually be a node versioning issue.  I added a couple of events to the stream and it appears to work ok.

```javascript
function writeScreenshot(data, filename) {
    var stream = fs.createWriteStream(filename);
    stream.on('finish', function(){ });
    stream.on('error', function(err){ });
    stream.write(new Buffer(data, 'base64'));
    stream.end();
  }
```

Can you verify?

**Comment by papa-pep** [comment]
I also noticed that the mkdirp function doesn't appear to adhere properly to the documentation.   It seems as though there should be a third parameter such as below:

```javascript
function ensureFolderExists(path) {
        if (path) {
            // replacing with mkdirp, because it works recursively
            mkdirp(path, null, function (err) {
                if (err) {
                    if (err.code == 'EEXIST') {
                        //AOK
                    } else {
                        console.error('Error creating trx output folder: ' + err);
                    }
                }
            });
        }
    }
```

https://www.npmjs.com/package/mkdirp

Please double check me on this too.

**Comment by tbowmo** [comment]
The fix for writeScreenshot appears to work, but only because it ignores all errors (you just define an empty function for 'error').

If I use the following for writeScreenshot:
```
  function writeScreenshot(data, filename) {
    var stream = fs.createWriteStream(filename);
    stream.on('finish', function(){ });
    stream.on('error', function(err){ console.log('error encountered'); });
    stream.write(new Buffer(data, 'base64'));
    stream.end();
  }
```

I get the following as output from the test

```
Jasmine started

  Spec A
    ✓ Test 1
    ✓ Test 2
    ✗ Test 3
      - Expected false to be true.
          at Object.<anonymous> (/home/thomas/t/jasmine-trx-report-fail/e2e/test-a.e2e-spec.ts:13:19)
          at step (/home/thomas/t/jasmine-trx-report-fail/e2e/test-a.e2e-spec.ts:32:23)
          at Object.next (/home/thomas/t/jasmine-trx-report-fail/e2e/test-a.e2e-spec.ts:13:53)
          at /home/thomas/t/jasmine-trx-report-fail/e2e/test-a.e2e-spec.ts:7:71
          at new Promise (<anonymous>)
          at __awaiter (/home/thomas/t/jasmine-trx-report-fail/e2e/test-a.e2e-spec.ts:3:12)
          at UserContext.<anonymous> (/home/thomas/t/jasmine-trx-report-fail/e2e/test-a.e2e-spec.ts:12:16)
          at /home/thomas/t/jasmine-trx-report-fail/node_modules/jasminewd2/index.js:112:25
          at new ManagedPromise (/home/thomas/t/jasmine-trx-report-fail/node_modules/selenium-webdriver/lib/promise.js:1067:7)

  Spec B
    ✓ test 4
error encountered
    ✓ test 5
    ✓ test 6
```

So the fix does remove the error, but it's like peeing in your pants to keep warm :), because now the screenshot is not written to the disk, in case of an error.

Btw. latest test is run on my private computer, running linux and using node 8.9.4, at work I'm using Windows 10, and node 8.9.3 to reproduce the issue.

**Comment by tbowmo** [comment]
Just tried Node 7.10.1 on my windows 10 computer. And it behaves the same way with my test example. So apparently it's not because of something changed in recent versions of node...

**Comment by tbowmo** [comment]
@papa-pep Thinking about solutions for this in the last couple of weeks, but can't come up with a real fix.

Could you make a release where we catch the errors while writing the image, your suggestion is probably the best solution at the moment. Then it's useful again, as it doesn't fail other tests because of the delayed write.

Should I make a PR?

```
function writeScreenshot(data, filename) {
    var stream = fs.createWriteStream(filename);
    stream.on('finish', function(){ });
    stream.on('error', function(err){ });
    stream.write(new Buffer(data, 'base64'));
    stream.end();
  }
```

**Comment by ninogomez** [comment]
Sorry for the dumb question. 

Looking at npmjs the version is still 2.2.2. Will this fix be published? Or how will I use this fix in my project?

**Comment by tbowmo** [comment]
Almost forgot this, I have an updated version on a local repository, with other changes as well, I'll make a PR in the coming week.

**Comment by ninogomez** [comment]
@tbowmo  Hi, sorry to bother you. Any update on the PR you mentioned? Thanks!
